/**
 * ⚠️ TEMPLATES ONLY - DO NOT USE DIRECTLY IN PRODUCTION
 * 
 * This file contains TEMPLATE DEFINITIONS for duplicating when creating new events.
 * 
 * ✅ What this file contains:
 *    - WPT_DEFAULT_TEMPLATE_* : Official WPT event template (to be duplicated)
 * 
 * ❌ What this file should NOT contain:
 *    - Real event instances (use Firestore instead)
 *    - Real categories linked to specific eventIds
 *    - Real user data or registrations
 *    - Real slot data
 *    - Real payments or vouchers
 * 
 * 🎯 How templates are used:
 *    1. User selects "Create from WPT Standard Template" in CreateEventModal
 *    2. App.tsx handleCreateEvent() is called
 *    3. New event is created with unique eventId
 *    4. Template data is DUPLICATED (not referenced) with new eventId
 *    5. All IDs are regenerated via Firestore
 *    6. Duplicated data is fully editable, no restrictions
 */

import { Category, Product } from "@/types/firestore";

// ============================================================================
// 📋 OFFICIAL WPT EVENT TEMPLATES
// ============================================================================
// These templates represent the standard World Pizza Trophy setup.
// They are hardcoded to ensure consistency for all future events.
// DO NOT MODIFY without explicit approval from event organizers.

/**
 * WPT Standard Category Template
 * Used when users select "Create from WPT Standard Template"
 * 
 * Properties to note:
 * - NO id (will be generated by Firestore on duplication)
 * - NO eventId (will be set to newEventId on duplication)
 * - NO activeDates (dates must be set per event instance)
 */
export const WPT_DEFAULT_TEMPLATE_CATEGORIES: Omit<Category, "id" | "eventId" | "activeDates">[] = [
  {
    name: 'Pizza Classique',
    description: 'La tradition italienne.',
    rules: 'Diamètre min 29cm.',
    unitPrice: 120,
    maxSlots: 60,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Calzone',
    description: 'Le classique replié.',
    rules: 'Pâte repliée, scellée.',
    unitPrice: 100,
    maxSlots: 30,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Pizza Dessert',
    description: 'Créations sucrées.',
    rules: 'Toppings sucrés uniquement.',
    unitPrice: 130,
    maxSlots: 30,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Napolitaine',
    description: 'Vera Pizza Napoletana.',
    rules: 'Certification Vera Pizza Napoletana.',
    unitPrice: 180,
    maxSlots: 20,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Focaccia',
    description: 'Pain plat à l\'huile d\'olive.',
    rules: 'Pain plat sans levain.',
    unitPrice: 80,
    maxSlots: 20,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Pasta',
    description: 'Travail de la pâte.',
    rules: 'Techniques de pâte traditionnelle.',
    unitPrice: 90,
    maxSlots: 20,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Pizza Douée',
    description: 'Compétition en duo.',
    rules: '2 pizzaiolos, 1 pizza.',
    unitPrice: 200,
    maxSlots: 10,
    durationMinutes: 20,
    isActive: true,
  },
  {
    name: 'Rapidité',
    description: 'Vitesse et précision.',
    rules: '5 minutes maximum.',
    unitPrice: 110,
    maxSlots: 20,
    durationMinutes: 5,
    isActive: true,
  },
  {
    name: 'Freestyle',
    description: 'Créativité totale.',
    rules: 'Libre cours à la créativité.',
    unitPrice: 140,
    maxSlots: 20,
    durationMinutes: 10,
    isActive: true,
  },
  {
    name: 'Large',
    description: 'Pizza grand format.',
    rules: 'Diamètre min 40cm.',
    unitPrice: 150,
    maxSlots: 20,
    durationMinutes: 20,
    isActive: true,
  },
  {
    name: 'Teglia',
    description: 'Pizza en plaque.',
    rules: 'Format en plaque rectangulaire.',
    unitPrice: 150,
    maxSlots: 25,
    durationMinutes: 15,
    isActive: true,
  },
  {
    name: 'Pala',
    description: 'Pizza alla pala.',
    rules: 'Format en pala (pelle).',
    unitPrice: 150,
    maxSlots: 25,
    durationMinutes: 15,
    isActive: true,
  },
];

/**
 * WPT Standard Product Template
 * Used when users select "Create from WPT Standard Template"
 * 
 * Properties to note:
 * - NO id (will be generated by Firestore on duplication)
 * - NO eventId (will be set to newEventId on duplication)
 * - stripePriceId may be placeholder (updated in Settings after creation)
 */
export const WPT_DEFAULT_TEMPLATE_PRODUCTS: Omit<Product, "id" | "eventId">[] = [
  {
    name: 'Pack Compétiteur OR',
    description: '3 catégories + repas VIP',
    stripePriceId: '', // Placeholder: Updated in Settings after creation
    unitAmount: 300,
    slotsRequired: 3,
    isPack: true,
    includesMeal: true,
    isActive: true,
  },
  {
    name: 'Pack Duo',
    description: '2 catégories pour 2 personnes',
    stripePriceId: '', // Placeholder: Updated in Settings after creation
    unitAmount: 180,
    slotsRequired: 2,
    isPack: true,
    includesMeal: false,
    isActive: true,
  },
];

// Legacy alias for backward compatibility
export const CATEGORY_TEMPLATES = WPT_DEFAULT_TEMPLATE_CATEGORIES;

// ============================================================================
// ⚠️ DEPRECATED: Real event data has been removed from this file
// ============================================================================
//
// The following data structures were previously in this file and have been
// removed to enforce clean separation between templates and real data:
//
// ❌ MOCK_EVENTS (evt_2025, evt_2026)
// ❌ INITIAL_CATEGORIES (linked to evt_2025)
// ❌ INITIAL_SLOTS (linked to evt_2025)
// ❌ INITIAL_USERS (Mario, Luigi, John, Phantom)
// ❌ MOCK_PRODUCTS (linked to evt_2025, evt_2026)
// ❌ MOCK_VOUCHERS (linked to evt_2025, evt_2026)
// ❌ MOCK_PAYMENTS (linked to evt_2025)
//
// These are now ONLY in Firestore (via admin panel creation or Firebase admin SDK).
// This ensures:
// - No hardcoded production data in source code
// - Clean separation between templates and real data
// - Proper lifecycle management via Firestore
// - No risk of accidentally committing sensitive information
//
// If you need to populate Firestore with test data for development, use:
// - Firebase Emulator Suite (local testing)
// - Admin SDK scripts in api/ directory
// - Firestore console (manual creation)
